on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: Ubuntu-latest

    steps:
      - name: "List all files"
        run: ls

      - uses: actions/checkout@v3

      - name: "List all files"
        run: ls
